OVERLAYS_TYPE = [
    "AREA", "ATTRIBUTE", "AVG", "COMBO", "DISTANCE", "FLOODING", 
    "FUNCTION", "GEO_TIFF", "GROUNDWATER", "HEAT_STRESS", "HEIGHTMAP", 
    "IMAGE", "LIVABILITY", "MUNICIPALITIES", "NEIGHBORHOODS", 
    "NETWORK_DISTANCE", "NETWORK_OVERVIEW", "NETWORK_OWNERSHIP", 
    "OWNERSHIP", "OWNERSHIP_GRID", "RAINFALL", "RESULT_CHILD", 
    "SIGHT_DISTANCE", "SOURCE", "SUBSIDENCE", "TEST", "TRAFFIC_DENSITY", 
    "TRAFFIC_NO2", "TRAFFIC_NOISE", "TRAVEL_DISTANCE", "UNDERGROUND", 
    "VACANCY", "WATERSHED", "WCS", "WMS", "ZIP_CODES", "ZONING"
]
TERRAIN_TYPE = []
FUNCTIONS_TYPE = []

BUILDING_TYPES = ["BUILDING","ROAD","UNDERGROUND"]
BUILDING_ATTRIBUTE_GROUPING = {
    "Building & Geometry": [
        "DEFAULT_FLOORS",
        "MAX_FLOORS",
        "MIN_FLOORS",
        "FLOOR_HEIGHT_M",
        "HEIGHT",
        "HEIGHT_OFFSET_M",
        "ROOF_COLOR",
        "POPULATION_DENSITY_M2"
    ],
    "Category Weights": [
        "EDUCATION_CATEGORY_WEIGHT",
        "HEALTHCARE_CATEGORY_WEIGHT",
        "LUXE_CATEGORY_WEIGHT",
        "NORMAL_CATEGORY_WEIGHT",
        "OFFICES_CATEGORY_WEIGHT",
        "OTHER_CATEGORY_WEIGHT",
        "SHOPPING_CATEGORY_WEIGHT",
        "SOCIAL_CATEGORY_WEIGHT"
    ],
    "Unit Sizes": [
        "LUXE_UNIT_SIZE_M2",
        "NORMAL_UNIT_SIZE_M2",
        "SOCIAL_UNIT_SIZE_M2"
    ],
    "Traffic": [
        "TRAFFIC_LANES",
        "MAX_SPEED_DYNAMIC",
        "JAM_FACTOR_CARS",
        "JAM_FACTOR_TRUCKS",
        "JAM_FACTOR_VANS",
        "NUM_CARS",
        "NUM_TRUCKS",
        "NUM_VANS",
        "NUM_LIGHT_VEHICLES_DYN"
    ],
    "Infrastructure": [
        "LENGTE",
        "BREEDTEOPENING",
        "HOOGTEOPENING",
        "CULVERT_DIAMETER",
        "KERENDEHOOGTE",
        "HOOGTEBINNENONDERKANTBENEDENSTROOMS",
        "HOOGTEBINNENONDERKANTBOVENSTROOMS",
        "LEFT_SHIELD_HEIGHT",
        "LEFT_TO_SHIELD_DISTANCE",
        "RIGHT_SHIELD_HEIGHT",
        "RIGHT_TO_SHIELD_DISTANCE"
    ],
    "Administration": [
        "BAG_ID",
        "NWB_ID",
        "CONSTRUCTION_FINISH_DATE"
    ]
}

