OVERLAYS_TYPE = [
    "AREA", "ATTRIBUTE", "AVG", "COMBO", "DISTANCE", "FLOODING", 
    "FUNCTION", "GEO_TIFF", "GROUNDWATER", "HEAT_STRESS", "HEIGHTMAP", 
    "IMAGE", "LIVABILITY", "MUNICIPALITIES", "NEIGHBORHOODS", 
    "NETWORK_DISTANCE", "NETWORK_OVERVIEW", "NETWORK_OWNERSHIP", 
    "OWNERSHIP", "OWNERSHIP_GRID", "RAINFALL", "RESULT_CHILD", 
    "SIGHT_DISTANCE", "SOURCE", "SUBSIDENCE", "TEST", "TRAFFIC_DENSITY", 
    "TRAFFIC_NO2", "TRAFFIC_NOISE", "TRAVEL_DISTANCE", "UNDERGROUND", 
    "VACANCY", "WATERSHED", "WCS", "WMS", "ZIP_CODES", "ZONING"
]

